name: Ruby CI

on:
  push:
    branches-ignore: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.4, 2.5, 2.6, 2.7 ]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Update system gems
        run: gem update --system
      - name: Install proper bundler gem
        run: gem install bundler -v 1.5.3
      - name: Uninstall previous bundler
        run: gem uninstall bundler -v 2.2.6
      - name: Install Ruby gems
        run: bundle _1.5.3_ install
      - name: Run rake spec tasks
        run: |
          rake engine_cart:clean
          rake ci